name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'modules-call/**'

  pull_request:
    branches:
      - main
    paths:
      - 'modules-call/**'
 
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform configuration'
        required: true
        default: 'modules-call'
      terraform_destroy:
        description: 'Run terraform plan -destroy'
        required: true
        default: 'false'

jobs:
  terraform:
    uses: ./.github/workflows/template.yml
    with:
      path: 'modules-call'
      terraform_destroy: false
    # secrets:
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
