name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'modules-call/**'

  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform configuration'
        required: true
        default: 'modules-call'
      terraform_destroy:
        description: 'Run terraform plan -destroy'
        required: true
        default: 'false'

jobs:
  plan-on-push-or-pr:
    if: github.event_name != 'workflow_dispatch'
    uses: ./.github/workflows/template.yml
    with:
      path: 'modules-call'
      terraform_destroy: 'false'
