name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'module-call/'

jobs:
  terraform:
    uses: ./github/workflows/template.yml
    with:
      path: 'module-call/'
      terraform_destroy: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
